language: node_js

before_install:
  - npm install -g gulp
  - wget http://archive.apache.org/dist/lucene/solr/5.1.0/solr-5.1.0.tgz
  - tar -xzf solr-5.1.0.tgz
  - export PATH=$PATH:$PWD/solr-5.1.0/bin/
  - export NODE_ENV=development

before_script:
  - solr start -cloud -V -m 4g -p 8983
  - sleep 15
  - solr create -c sieveable-code
  - solr create -c sieveable-ui-tag
  - solr create -c sieveable-ui-suffix
  - solr create -c sieveable-manifest
  - gulp

script:
  # Make sure Solr is running.
  - curl http://localhost:8983/solr/admin/collections?action=LIST&wt=json
  - npm test

after_success:
  - npm run coveralls

after_script:
  # Delete Solr Collections
  - solr delete -c sieveable-ui-tag -deleteConfig true
  - solr delete -c sieveable-ui-suffix -deleteConfig true
  - solr delete -c sieveable-manifest -deleteConfig true
  - solr delete -c sieveable-code -deleteConfig true
  - solr stop

node_js:
  - "0.12"

jdk:
  - oraclejdk7

services:
  - mongodb
  - redis-server

sudo: false

notifications:
  email: false
  slack:
    secure: ZMjCr3IV5/frTvI91Tb2516pY/0ofZ0CqIBYy84tczMfwtpKvkPFBqo0xW/bGrQ5AoMwFQG3UdYJ9334j4Ayj+gscQVuAoqp032Eql4hhUBfHYQr10/LfdcKvKD2ebSFhtO6SMyNlHRk9sCHTGqKdiRLf3Wp44ejcpxaG+RMeoE=
