language: node_js

node_js:
  - "0.12"

env:
  global:
    # Solr 5.1
    - SOLR_VERSION="5.1.0"
    - SOLR_DOWNLOAD="http://archive.apache.org/dist/lucene/solr/"
    - SOLR_FILE="solr-5.1.0.tgz"
    - SOLR_INSTALL_DIR=$TRAVIS_BUILD_DIR/srv/solr-5.1.0
    - SOLR_OPTS="-cloud -V -m 4g -p 8983"
    # MongoDB 3.0
    - MONGODB_DOWNLOAD="https://fastdl.mongodb.org/linux/"
    - MONGODB_FILE="mongodb-linux-x86_64-ubuntu1204-3.0.4.tgz"
    - MONGODB_TARGET_FILE="mongodb-3.0.4.tgz"
    - MONGODB_INSTALL_DIR=$TRAVIS_BUILD_DIR/srv/mongodb-3.0.4
    - MONGODB_LOG_DIR=$TRAVIS_BUILD_DIR/srv/log/mongodb
    - MONGODB_DATA_DIR=$TRAVIS_BUILD_DIR/srv/mongodb/data
    - MONGODB_OPTS="--port 27017 --fork --logpath ${MONGODB_LOG_DIR} --dbpath ${MONGODB_DATA_DIR}"
  matrix:
    - NODE_ENV=development

before_install:
  - mkdir -p ${SOLR_INSTALL_DIR}
  - mkdir -p ${MONGODB_INSTALL_DIR}
  - mkdir -p ${MONGODB_LOG_DIR}
  - mkdir -p ${MONGODB_DATA_DIR}
  # Solr
  - curl -O ${SOLR_DOWNLOAD}${SOLR_VERSION}/${SOLR_FILE}
  # MongoDB
  - curl -O ${MONGODB_DOWNLOAD}${MONGODB_FILE}
  - mv ${MONGODB_FILE} ${MONGODB_TARGET_FILE}
  # Gulp
  - npm install -g gulp

install:
  # Solr
  - tar -zxvf ${SOLR_FILE} -C ${SOLR_INSTALL_DIR} --strip-components 1
  - export PATH=${SOLR_INSTALL_DIR}/bin:$PATH
  # MongoDB
  - tar -zxvf ${MONGODB_TARGET_FILE} -C ${MONGODB_INSTALL_DIR} --strip-components 1
  - export PATH=${MONGODB_INSTALL_DIR}/bin:$PATH

before_script:
  # Start Solr
  - solr start ${SOLR_OPTS}
  - "until nc -z localhost 8983; do echo Waiting for Solr; sleep 1; done"
  - solr create -c sieveable-code
  - solr create -c sieveable-ui-tag
  - solr create -c sieveable-ui-suffix
  - solr create -c sieveable-manifest
  # Start MongoDB
  - mongod --version
  - mongod ${MONGODB_OPTS}
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  # Kick off the default gulp task
  - gulp

script:
  # Test the server
  - npm test

after_success:
  # Report test coverage
  - npm run coveralls

after_script:
  # Delete Solr Collections
  - solr delete -c sieveable-ui-tag -deleteConfig true
  - solr delete -c sieveable-ui-suffix -deleteConfig true
  - solr delete -c sieveable-manifest -deleteConfig true
  - solr delete -c sieveable-code -deleteConfig true
  # Stop Solr
  - solr stop
  # Stop MongoDB
  - mongod --shutdown
  # Delete data dirs
  - rm -rf ${MONGODB_DATA_DIR}
  - rm -rf ${MONGODB_LOG_DIR}

jdk:
  - oraclejdk7

services:
  - redis-server

sudo: false

notifications:
  email: false
  #slack:
    #secure: ZMjCr3IV5/frTvI91Tb2516pY/0ofZ0CqIBYy84tczMfwtpKvkPFBqo0xW/bGrQ5AoMwFQG3UdYJ9334j4Ayj+gscQVuAoqp032Eql4hhUBfHYQr10/LfdcKvKD2ebSFhtO6SMyNlHRk9sCHTGqKdiRLf3Wp44ejcpxaG+RMeoE=
