language: node_js
before_install:
  - npm install -g gulp
before_script:
  - gulp build:tagname
services:
  - mongodb
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
sudo: false
notifications:
  email: false
