language: node_js

before_install:
  - npm install -g gulp
  - wget http://archive.apache.org/dist/lucene/solr/5.1.0/solr-5.1.0.tgz
  - tar -xzf solr-5.1.0.tgz
  - export PATH=$PATH:$PWD/solr-5.1.0/bin/
  - export NODE_ENV=development

before_script:
  - solr start -cloud -V -m 4g -p 8983
  - sleep 15
  - solr create -c sieveable-code
  - solr create -c sieveable-ui-tag
  - solr create -c sieveable-ui-h-tag
  - sleep 10
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"package_name", "type":"string", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-code/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"version_code", "type":"int", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-code/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"package_name", "type":"string", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-ui-tag/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"version_code", "type":"int", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-ui-tag/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"package_name", "type":"string", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-ui-h-tag/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"version_code", "type":"int", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-ui-h-tag/schema
  - gulp
  - gulp load:db
  - gulp index:ui
  - gulp solr:indexCode
  - gulp solr:commit

script:
  # Make sure Solr is running.
  - curl http://localhost:8983/solr/admin/collections?action=LIST&wt=json
  - npm test

after_success:
  - npm run coveralls

after_script:
  # Delete indexed documents and stop solr
  - curl http://localhost:8983/solr/sieveable-code/update --data '<delete><query>*:*</query></delete>' -H 'Content-type:text/xml; charset=utf-8'
  - curl http://localhost:8983/solr/sieveable-code/update --data '<commit/>' -H 'Content-type:text/xml; charset=utf-8'
  - curl http://localhost:8983/solr/admin/collections?action=DELETE&name=sieveable-code
  - solr stop

node_js:
  - "0.12"

jdk:
  - oraclejdk7

services:
  - mongodb
  - redis-server

sudo: false

notifications:
  email: false