language: node_js
node_js:
  - "5.7"

services:
  - redis-server
jdk:
  - oraclejdk7

env:
  global:
    # Solr 5.5
    - SOLR_VERSION="5.5.0"
    - SOLR_DOWNLOAD="http://archive.apache.org/dist/lucene/solr/"
    - SOLR_FILE="solr-5.5.0.tgz"
    - SOLR_INSTALL_DIR=$TRAVIS_BUILD_DIR/srv/solr-5.5.0
    - SOLR_PORT=8983
    - SOLR_OPTS="-cloud -V -m 1g -p $SOLR_PORT"
  matrix:
    - NODE_ENV=development

before_install:
  - mkdir -p ${SOLR_INSTALL_DIR}
  # Solr
  - curl -O ${SOLR_DOWNLOAD}${SOLR_VERSION}/${SOLR_FILE}

install:
  # Solr
  - tar -zxf ${SOLR_FILE} -C ${SOLR_INSTALL_DIR} --strip-components 1
  - export PATH=${SOLR_INSTALL_DIR}/bin:$PATH
  # Gulp
  - npm install -g gulp
  - npm install

before_script:
  # Start Solr
  - solr start ${SOLR_OPTS}
  - solr create -c sieveable-listing -p ${SOLR_PORT}
  - solr create -c sieveable-code -p ${SOLR_PORT}
  - solr create -c sieveable-ui-tag -p ${SOLR_PORT}
  - solr create -c sieveable-ui-suffix -p ${SOLR_PORT}
  - solr create -c sieveable-manifest -p ${SOLR_PORT}
  # Kick off the default gulp task
  - gulp

script:
  # Test the server
  - npm test

after_success:
  # Report test coverage
  - npm run coveralls

after_script:
  # Delete Solr Collections
  - solr delete -c sieveable-ui-tag -deleteConfig true -p ${SOLR_PORT}
  - solr delete -c sieveable-ui-suffix -deleteConfig true -p ${SOLR_PORT}
  - solr delete -c sieveable-manifest -deleteConfig true -p ${SOLR_PORT}
  - solr delete -c sieveable-code -deleteConfig true -p ${SOLR_PORT}
  - solr delete -c sieveable-listing -deleteConfig true -p ${SOLR_PORT}
  # Stop Solr
  - solr stop -p ${SOLR_PORT}

sudo: false

notifications:
  email: false
  slack:
    secure: ZMjCr3IV5/frTvI91Tb2516pY/0ofZ0CqIBYy84tczMfwtpKvkPFBqo0xW/bGrQ5AoMwFQG3UdYJ9334j4Ayj+gscQVuAoqp032Eql4hhUBfHYQr10/LfdcKvKD2ebSFhtO6SMyNlHRk9sCHTGqKdiRLf3Wp44ejcpxaG+RMeoE=
