language: node_js
before_install:
  - npm install -g gulp
  - wget http://archive.apache.org/dist/lucene/solr/5.1.0/solr-5.1.0.tgz && tar -xzf solr-5.1.0.tgz && sh solr-5.1.0/bin/solr start -cloud -V -m 4g
before_script:
  - sleep 20
  - sh solr-5.1.0/bin/solr create -c sieveable-code
  - sleep 10
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"package_name", "type":"string", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-code/schema
  - curl -X POST -H 'Content-type:application/json' --data-binary '{ "add-field":{ "name":"version_code", "type":"int", "indexed":true, "required":true, "stored":true } }' http://localhost:8983/solr/sieveable-code/schema
  - gulp
services:
  - mongodb
node_js:
  - '0.12'
sudo: false
notifications:
  email: false
