language: node_js
node_js:
  - "5.7"

services:
  - redis-server
jdk:
  - oraclejdk7

env:
  global:
    # Solr 5.1
    - SOLR_VERSION="5.1.0"
    - SOLR_DOWNLOAD="http://archive.apache.org/dist/lucene/solr/"
    - SOLR_FILE="solr-5.1.0.tgz"
    - SOLR_INSTALL_DIR=$TRAVIS_BUILD_DIR/srv/solr-5.1.0
    - SOLR_OPTS="-cloud -V -m 4g -p 8983"
  matrix:
    - NODE_ENV=development

before_install:
  - mkdir -p ${SOLR_INSTALL_DIR}
  # Solr
  - curl -O ${SOLR_DOWNLOAD}${SOLR_VERSION}/${SOLR_FILE}

install:
  # Solr
  - tar -zxvf ${SOLR_FILE} -C ${SOLR_INSTALL_DIR} --strip-components 1
  - export PATH=${SOLR_INSTALL_DIR}/bin:$PATH
  # Gulp
  - npm install -g gulp
  - npm install

before_script:
  # Start Solr
  - solr start ${SOLR_OPTS}
  - "until nc -z localhost 8983; do echo Waiting for Solr; sleep 1; done"
  - solr create -c sieveable-listing
  - solr create -c sieveable-code
  - solr create -c sieveable-ui-tag
  - solr create -c sieveable-ui-suffix
  - solr create -c sieveable-manifest
  # Kick off the default gulp task
  - gulp

script:
  # Test the server
  - npm test

after_success:
  # Report test coverage
  - npm run coveralls

after_script:
  # Delete Solr Collections
  - solr delete -c sieveable-ui-tag -deleteConfig true
  - solr delete -c sieveable-ui-suffix -deleteConfig true
  - solr delete -c sieveable-manifest -deleteConfig true
  - solr delete -c sieveable-code -deleteConfig true
  # Stop Solr
  - solr stop

sudo: false

notifications:
  email: false
  slack:
    secure: ZMjCr3IV5/frTvI91Tb2516pY/0ofZ0CqIBYy84tczMfwtpKvkPFBqo0xW/bGrQ5AoMwFQG3UdYJ9334j4Ayj+gscQVuAoqp032Eql4hhUBfHYQr10/LfdcKvKD2ebSFhtO6SMyNlHRk9sCHTGqKdiRLf3Wp44ejcpxaG+RMeoE=
