language: node_js
node_js:
  - "6"

jdk:
  - oraclejdk7

env:
  global:
    # Solr 5.1
    - SOLR_VERSION="5.1.0"
    - SOLR_DOWNLOAD="http://archive.apache.org/dist/lucene/solr/"
    - SOLR_FILE=solr-$SOLR_VERSION.tgz
    - SOLR_INSTALL_DIR=$TRAVIS_BUILD_DIR/srv/solr-$SOLR_VERSION
  matrix:
    - NODE_ENV=development

before_install:
  - mkdir -p ${SOLR_INSTALL_DIR}
  # Solr
  - curl -O ${SOLR_DOWNLOAD}${SOLR_VERSION}/${SOLR_FILE}

install:
  # Solr
  - tar -zxf ${SOLR_FILE} -C ${SOLR_INSTALL_DIR} --strip-components 1
  - export PATH=${SOLR_INSTALL_DIR}/bin:$PATH
  - npm install

before_script:
  - bash ./scripts/solr-startup.sh
  # Kick off the default build task
  - npm run build

script:
  # Test the server
  - npm test

after_success:
  # Report test coverage
  - npm run coveralls

after_script:
  - bash ./scripts/solr-teardown.sh

sudo: false

notifications:
  email: false
  slack:
    secure: ZMjCr3IV5/frTvI91Tb2516pY/0ofZ0CqIBYy84tczMfwtpKvkPFBqo0xW/bGrQ5AoMwFQG3UdYJ9334j4Ayj+gscQVuAoqp032Eql4hhUBfHYQr10/LfdcKvKD2ebSFhtO6SMyNlHRk9sCHTGqKdiRLf3Wp44ejcpxaG+RMeoE=
